apiVersion: v1
kind: Service
metadata:
  labels:
    app: modamatch
    tier: frontend
  name: modamatch
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 3000
      protocol: TCP
  selector:
    app: modamatch
    tier: frontend
  # sessionAffinity: None
